openapi: 3.0.0
info:
  title: Swagger Petstore
  version: 1.0.0
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: ./models/pet.v1.yaml
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '../common/models/common.v1.yaml#/components/schemas/Error'
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: ./models/pets.v1.yaml
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/pet.v1.yaml
components:
  securitySchemes:
    API Key - Header:
      name: Authorization
      type: apiKey
      in: header
